apiVersion: external-secrets.io/v1beta1
kind: SecretStore 
metadata: 
  name: azure-keyvault-store
  namespace: production
spec: 
  provider: 
    azurekv: 
      url: "https://my-keyvault.vault.azure.net/"
      authType: WorkloadIdentity 
      serviceAccountRef:
        name: app-service-account 

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret 
metadata: 
  name: mysql-credentials 
  namesapce: production 
spec: 
  refreshInterval: 1h 
  secretStoreRef:
    name: azure-keyvault-store
    kind: SecretStore
  target: 
    name: mysql-secret
    creationPolicy: Owner 
  data: 
  - secretKey: root_password 
    remoteRef: 
      key: mysql-root-password 
  - secretKey: database_name 
    remoteRef: 
      key: mysql-database-name