apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: azure-keyvault-store
  namespace: production
spec:
  provider:
    azurekv:
      url: "https://${KEYVAULT_NAME}.vault.azure.net/"
      authType: WorkloadIdentity
      serviceAccountRef:
        name: app-service-account
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-credentials
  namespace: production
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: azure-keyvault-store
    kind: SecretStore
  target:
    name: mysql-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        MYSQL_ROOT_PASSWORD: "{{ .mysql_root_password }}"
        MYSQL_USER: "{{ .mysql_user }}"
        MYSQL_PASSWORD: "{{ .mysql_password }}"
        MYSQL_DATABASE: "{{ .mysql_database }}"
  data:
  - secretKey: mysql_root_password
    remoteRef:
      key: mysql-root-password
  - secretKey: mysql_user
    remoteRef:
      key: mysql-user
  - secretKey: mysql_password
    remoteRef:
      key: mysql-password
  - secretKey: mysql_database
    remoteRef:
      key: mysql-database
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-secrets
  namespace: production
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: azure-keyvault-store
    kind: SecretStore
  target:
    name: app-secret
    creationPolicy: Owner
  data:
  - secretKey: jwt_secret
    remoteRef:
      key: jwt-secret-key
  - secretKey: api_key
    remoteRef:
      key: api-key