apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata: 
  name: "webapp-azure-key"
  namespace: production 
spec: 
  provider: azure 
  parameters: 
    usePodIdentity: "false" 
