apiVersion: v1 
kind: Namespace
metadata:
  name: production
  labels: 
    name: production
    environment: production
    team: ops 

---
apiVersion: v1 
kind: ServiceAccount
metadata: 
  name: app-service-account 
  namespace: production
  annotations: 
    azure.workload.identity-id: "my-client-id"
    

