apiVersion: autoscaling/v2 
kind: HorizontalPodAutoscaler 
metadata: 
  name: frontend-hpa 
  namespace: production 
spec: 
  scaleTargetRef: 
    apiVersion: apps/v1 
    kind: Deployment 
    name: frontend-app-deployment
  minreplicas: 3 
  maxReplicas: 10 
  metrics: 
  - type: Resource 
    resources: 
      name: cpu 
      target: 
        type: Utilization 
        averageUtilization: 70 
  - type: Resource 
    resources: 
      name: memory 
      target: 
        type: Utilization 
        averageUtilization: 80

        