apiVersion: v1 
kind: Services 
metadata: 
  name: backend-db 
  namespace: production 
  lables: 
    app: app-backend 
    tier: database 
  spec: 
    selector: 
      app: app-backend 
      tier: database 
    ports: 
    - name: mysql 
      port: 3306 
      targetPort: 3306 
      protocol: TCP 
    type: ClusterIP

--- 
apiVersion: v1 
kind: Services 
metadata: 
  name: frontend-service 
  namespace: production 
  labels: 
    app: app-frontend 
    tier: frontend 
spec:
  selector: 
    app: app-frontend 
    tier: frontend 
  ports: 
  - name: http 
    port: 80 
    targetPort: 80 
    protocol: TCP
  type: ClusterIP 
    