apiVersion: policy/v1 
kind: PodDistributionBudget
metadata: 
  name: frontend-pdb 
  namespace: production 
spec: 
  minAvailable: 2 
  selector: 
    matchLabels: 
      app: app-frontend 
      tier: frontend 

--- 
apiVersion: policy/v1 
kind: PodDistributionBudget
metadata: 
  name: backend-pdb 
  namespace: production
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: app-backend
      tier: database