apiVersion: v1 
kind: PersistentVolumeClaim 
metadata: 
  name: mysql-pvc 
  namespace: production 
spec: 
  accessModes: 
  - readWriteOnce 
  resources: 
    requests: 
      storage: 5Gi 
  storageClassName: local-path 