apiVersion: v1
kind: Service
metadata:
  name: backend-db
  labels:
    app: app-backend
spec:
  selector:
    app: app-backend
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
      protocol: TCP
  type: ClusterIP