apiVersion: v1 
kind: Service 
metadata: 
  name: frontend-service 
  labels: 
    app: app-frontend 
spec: 
  selector: 
    app: app-frontend
  ports: 
   - name: http
     port: 80 
     targetPort: 80 
     nodePort: 30080
     protocol: TCP
  type: NodePort