apiVersion: v1 
kind: StatefulSet 
metadata: 
  name: mysql-statefulset 
  namespace: production 
  labels:
    app: app-backend
    tier: database 
    environment: production
spec: 
  serviceName: mysql-headless-service 
  replicas: 1 
  selector: 
    matchLabels: 
      app: app-backend 
      tier: database
  template: 
    metadata: 
      labels: 
        app: app-backend
        tier: database 
        environment: production
    spec: 
      securityContext:
        fsGroup: 999
      containers:
      - name: mysql
        image: mysql:8.0.43
        imagePullPolicy: always 
        ports: 
        - containerPort: 3306 
          name: mysql 
        env: 
        - name: MYSQL_ROOT_PASSWORD 
          valueFrom: 
            secretKeyRef: 
              name: mysql-credentials
              key: MYSQL_ROOT_PASSWORD 

        - name: MYSQL_USER 
          valueFrom: 
            secretKeyRef: 
              name: mysql-credentials
              key: MYSQL_USER 

        - name: MYSQL_PASSWORD 
          valueFrom: 
            secretKeyRef: 
              name: mysql-credentials
              key: MYSQL_PASSWORD 

        - name: MYSQL_DATABASE  
          valueFrom: 
            secretKeyRef: 
              name: mysql-credentials
              key: MYSQL_DATABASE 

        resources: 
          requests: 
            memory: "512Mi" 
            cpu: "200m" 
          limits: 
            memory: "1Gi" 
            cpu: "500m"
        volumeMounts: 
        - name: mysql-persistent-storage 
          mountPath: /var/lib/mysql 
        - name: mysql-config 
          mountPath: /etc/mysql/conf.d 
        - name: secrets-store 
          mountPath: /mnt/secrets-store 
          readOnly: true 
        livenessProbe: 
          exec: 
            command: 
            - mysqladmin
            - ping 
            - -host=localhost
          initialDelaySeconds: 30 
          timeoutSeconds: 5 
          periodSeconds: 10 
          failureThreshold: 3 
        readinessProbe: 
          exec: 
            command: 
            - mysql 
            - -h 
            - localhost 
            - -U 
            - root 
            - -p$MYSQL_ROOT_PASSWORD
            - -e 
            - "SELECT 1" 
          initalDelaySeconds: 10 
          timeoutSeconds: 2 
          periodSeconds: 5 
          failureThreshold: 3 
        securitycontext: 
          runAsNonRoot: true 
          runAsUser: 999 
          runAsGroup: 999 
          allowPrivilegeescalation: false 
          capabilities: 
            drop: 
            - ALL 
      volumes: 
      - name: mysql-config 
        configMap: 
          name: mysql-config
      - name: secrets-store 
        csi: 
          driver: secrets-store.csi.k8s.io
          readOnly: true 
          volumeAttributes:
            secretProviderClass: "webapp-azure-key"
          nodePublishsecret: 
            name: secrets-store-creds 
      restartPolicy: Always 
    volumeClaimtemplates: 
    - metadata: 
        name: mysql-persistent-storage 
      spec: 
        accessModes: ["ReadWriteOnce"] 
        storageClassName: local-path  
        resources: 
          requests: 
            storage: 5Gi 

 



    